### Post 517
**Post URL**: /t/project-1-llm-based-automation-agent-discussion-thread-tds-jan-2025/164277/517
- **ID**: 595859
- **Author**: Monisha M (23f3002091)
- **Created At**: 2025-02-16T10:12:11.868Z
- **Content**:  
  uv run <a href="https://raw.githubusercontent.com/sanand0/tools-in-data-science-public/tds-2025-01/project-1/evaluate.py" rel="noopener nofollow ugc">https://raw.githubusercontent.com/sanand0/tools-in-data-science-public/tds-2025-01/project-1/evaluate.py</a><br>
Installed 13 packages in 543ms<br>
Traceback (most recent call last):<br>
File “/tmp/evaluateF6zgG9.py”, line 20, in <br>
from datagen import (<br>
…&lt;9 lines&gt;…<br>
)<br>
ModuleNotFoundError: No module named ‘datagen’
I am getting this error when I try to run evaluate.py
when I run the evaluate.py by having datagen.py in same folder , it is running perfectly. But my doubt is only after task a1 runs the datagen.py will be downloaded into the /data folder right ?
<a class="mention" href="/u/carlton">@carlton</a> <a class="mention" href="/u/saransh_saini">@Saransh_Saini</a> <a class="mention" href="/u/jivraj">@Jivraj</a><br>
Kindly help me with this issue
- **Reactions**: None
- **Post Number**: 517

